behaviors:
  CatcherCurriculumL:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 20000
    threaded: true
environment_parameters:
  team_size:
    curriculum:
      - name: Blocking5
        completion_criteria:
          measure: reward
          behavior: CatcherCurriculumL
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 5
            max_value: 5
      - name: Blocking5+
        completion_criteria:
          measure: reward
          behavior: CatcherCurriculumL
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 5
            max_value: 7
      - name: Blocking7+
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 7
            max_value: 10